# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import common_pb2 as proto_dot_common__pb2
from proto import payment_pb2 as proto_dot_payment__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddFunds = channel.unary_unary(
                '/payment.PaymentService/AddFunds',
                request_serializer=proto_dot_payment__pb2.AddFundsRequest.SerializeToString,
                response_deserializer=proto_dot_common__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/payment.PaymentService/ProcessPayment',
                request_serializer=proto_dot_payment__pb2.PaymentRequest.SerializeToString,
                response_deserializer=proto_dot_payment__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.FindUser = channel.unary_unary(
                '/payment.PaymentService/FindUser',
                request_serializer=proto_dot_payment__pb2.FindUserRequest.SerializeToString,
                response_deserializer=proto_dot_payment__pb2.FindUserResponse.FromString,
                _registered_method=True)
        self.VibeCheckTransactionStatus = channel.unary_unary(
                '/payment.PaymentService/VibeCheckTransactionStatus',
                request_serializer=proto_dot_common__pb2.TransactionStatus.SerializeToString,
                response_deserializer=proto_dot_common__pb2.TransactionStatus.FromString,
                _registered_method=True)
        self.PrepareSnapshot = channel.unary_unary(
                '/payment.PaymentService/PrepareSnapshot',
                request_serializer=proto_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_common__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.CheckSnapshotReady = channel.unary_unary(
                '/payment.PaymentService/CheckSnapshotReady',
                request_serializer=proto_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_common__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_unary(
                '/payment.PaymentService/Snapshot',
                request_serializer=proto_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_common__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/payment.PaymentService/Rollback',
                request_serializer=proto_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_common__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.ContinueConsuming = channel.unary_unary(
                '/payment.PaymentService/ContinueConsuming',
                request_serializer=proto_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_common__pb2.OperationResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddFunds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VibeCheckTransactionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSnapshotReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContinueConsuming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddFunds': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFunds,
                    request_deserializer=proto_dot_payment__pb2.AddFundsRequest.FromString,
                    response_serializer=proto_dot_common__pb2.OperationResponse.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=proto_dot_payment__pb2.PaymentRequest.FromString,
                    response_serializer=proto_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'FindUser': grpc.unary_unary_rpc_method_handler(
                    servicer.FindUser,
                    request_deserializer=proto_dot_payment__pb2.FindUserRequest.FromString,
                    response_serializer=proto_dot_payment__pb2.FindUserResponse.SerializeToString,
            ),
            'VibeCheckTransactionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.VibeCheckTransactionStatus,
                    request_deserializer=proto_dot_common__pb2.TransactionStatus.FromString,
                    response_serializer=proto_dot_common__pb2.TransactionStatus.SerializeToString,
            ),
            'PrepareSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareSnapshot,
                    request_deserializer=proto_dot_common__pb2.Empty.FromString,
                    response_serializer=proto_dot_common__pb2.OperationResponse.SerializeToString,
            ),
            'CheckSnapshotReady': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSnapshotReady,
                    request_deserializer=proto_dot_common__pb2.Empty.FromString,
                    response_serializer=proto_dot_common__pb2.OperationResponse.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=proto_dot_common__pb2.Empty.FromString,
                    response_serializer=proto_dot_common__pb2.OperationResponse.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=proto_dot_common__pb2.Empty.FromString,
                    response_serializer=proto_dot_common__pb2.OperationResponse.SerializeToString,
            ),
            'ContinueConsuming': grpc.unary_unary_rpc_method_handler(
                    servicer.ContinueConsuming,
                    request_deserializer=proto_dot_common__pb2.Empty.FromString,
                    response_serializer=proto_dot_common__pb2.OperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddFunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/AddFunds',
            proto_dot_payment__pb2.AddFundsRequest.SerializeToString,
            proto_dot_common__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/ProcessPayment',
            proto_dot_payment__pb2.PaymentRequest.SerializeToString,
            proto_dot_payment__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/FindUser',
            proto_dot_payment__pb2.FindUserRequest.SerializeToString,
            proto_dot_payment__pb2.FindUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VibeCheckTransactionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/VibeCheckTransactionStatus',
            proto_dot_common__pb2.TransactionStatus.SerializeToString,
            proto_dot_common__pb2.TransactionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/PrepareSnapshot',
            proto_dot_common__pb2.Empty.SerializeToString,
            proto_dot_common__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSnapshotReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/CheckSnapshotReady',
            proto_dot_common__pb2.Empty.SerializeToString,
            proto_dot_common__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/Snapshot',
            proto_dot_common__pb2.Empty.SerializeToString,
            proto_dot_common__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/Rollback',
            proto_dot_common__pb2.Empty.SerializeToString,
            proto_dot_common__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ContinueConsuming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/ContinueConsuming',
            proto_dot_common__pb2.Empty.SerializeToString,
            proto_dot_common__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
