# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/payment.proto\x12\x07payment\x1a\x12proto/common.proto\"\'\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63redit\x18\x02 \x01(\x05\"%\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"2\n\x0f\x41\x64\x64\x46undsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"1\n\x0ePaymentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"\"\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"B\n\x14\x42\x61tchUserInitRequest\x12\x11\n\tnum_users\x18\x01 \x01(\x05\x12\x17\n\x0fstarting_credit\x18\x02 \x01(\x05\x32\x84\x02\n\x0ePaymentService\x12\x38\n\nCreateUser\x12\r.common.Empty\x1a\x1b.payment.CreateUserResponse\x12\x33\n\x08\x41\x64\x64\x46unds\x12\x18.payment.AddFundsRequest\x1a\r.common.Empty\x12\x43\n\x0eProcessPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\x12>\n\x0e\x42\x61tchInitUsers\x12\x1d.payment.BatchUserInitRequest\x1a\r.common.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=52
  _globals['_USER']._serialized_end=91
  _globals['_CREATEUSERRESPONSE']._serialized_start=93
  _globals['_CREATEUSERRESPONSE']._serialized_end=130
  _globals['_ADDFUNDSREQUEST']._serialized_start=132
  _globals['_ADDFUNDSREQUEST']._serialized_end=182
  _globals['_PAYMENTREQUEST']._serialized_start=184
  _globals['_PAYMENTREQUEST']._serialized_end=233
  _globals['_PAYMENTRESPONSE']._serialized_start=235
  _globals['_PAYMENTRESPONSE']._serialized_end=269
  _globals['_BATCHUSERINITREQUEST']._serialized_start=271
  _globals['_BATCHUSERINITREQUEST']._serialized_end=337
  _globals['_PAYMENTSERVICE']._serialized_start=340
  _globals['_PAYMENTSERVICE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
