global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:5000/metrics']
  - job_name: 'stock-service'
    static_configs:
      - targets: ['stock-service:5000/metrics']
  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service:5000/metrics']
