# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import common_pb2 as proto_dot_common__pb2
from proto import order_pb2 as proto_dot_order__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/order.OrderService/CreateOrder',
                request_serializer=proto_dot_order__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=proto_dot_order__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.FindOrder = channel.unary_unary(
                '/order.OrderService/FindOrder',
                request_serializer=proto_dot_order__pb2.OrderRequest.SerializeToString,
                response_deserializer=proto_dot_order__pb2.Order.FromString,
                _registered_method=True)
        self.AddItem = channel.unary_unary(
                '/order.OrderService/AddItem',
                request_serializer=proto_dot_order__pb2.AddItemRequest.SerializeToString,
                response_deserializer=proto_dot_order__pb2.Order.FromString,
                _registered_method=True)
        self.Checkout = channel.unary_unary(
                '/order.OrderService/Checkout',
                request_serializer=proto_dot_order__pb2.OrderRequest.SerializeToString,
                response_deserializer=proto_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.BatchInitOrders = channel.unary_unary(
                '/order.OrderService/BatchInitOrders',
                request_serializer=proto_dot_order__pb2.BatchOrderInitRequest.SerializeToString,
                response_deserializer=proto_dot_common__pb2.Empty.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInitOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=proto_dot_order__pb2.CreateOrderRequest.FromString,
                    response_serializer=proto_dot_order__pb2.CreateOrderResponse.SerializeToString,
            ),
            'FindOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.FindOrder,
                    request_deserializer=proto_dot_order__pb2.OrderRequest.FromString,
                    response_serializer=proto_dot_order__pb2.Order.SerializeToString,
            ),
            'AddItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItem,
                    request_deserializer=proto_dot_order__pb2.AddItemRequest.FromString,
                    response_serializer=proto_dot_order__pb2.Order.SerializeToString,
            ),
            'Checkout': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkout,
                    request_deserializer=proto_dot_order__pb2.OrderRequest.FromString,
                    response_serializer=proto_dot_common__pb2.Empty.SerializeToString,
            ),
            'BatchInitOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInitOrders,
                    request_deserializer=proto_dot_order__pb2.BatchOrderInitRequest.FromString,
                    response_serializer=proto_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('order.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderService/CreateOrder',
            proto_dot_order__pb2.CreateOrderRequest.SerializeToString,
            proto_dot_order__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderService/FindOrder',
            proto_dot_order__pb2.OrderRequest.SerializeToString,
            proto_dot_order__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderService/AddItem',
            proto_dot_order__pb2.AddItemRequest.SerializeToString,
            proto_dot_order__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderService/Checkout',
            proto_dot_order__pb2.OrderRequest.SerializeToString,
            proto_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInitOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.OrderService/BatchInitOrders',
            proto_dot_order__pb2.BatchOrderInitRequest.SerializeToString,
            proto_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
