# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import common_pb2 as proto_dot_common__pb2
from proto import payment_pb2 as proto_dot_payment__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/payment.PaymentService/CreateUser',
                request_serializer=proto_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_payment__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.AddFunds = channel.unary_unary(
                '/payment.PaymentService/AddFunds',
                request_serializer=proto_dot_payment__pb2.AddFundsRequest.SerializeToString,
                response_deserializer=proto_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/payment.PaymentService/ProcessPayment',
                request_serializer=proto_dot_payment__pb2.PaymentRequest.SerializeToString,
                response_deserializer=proto_dot_payment__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.BatchInitUsers = channel.unary_unary(
                '/payment.PaymentService/BatchInitUsers',
                request_serializer=proto_dot_payment__pb2.BatchUserInitRequest.SerializeToString,
                response_deserializer=proto_dot_common__pb2.Empty.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFunds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInitUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=proto_dot_common__pb2.Empty.FromString,
                    response_serializer=proto_dot_payment__pb2.CreateUserResponse.SerializeToString,
            ),
            'AddFunds': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFunds,
                    request_deserializer=proto_dot_payment__pb2.AddFundsRequest.FromString,
                    response_serializer=proto_dot_common__pb2.Empty.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=proto_dot_payment__pb2.PaymentRequest.FromString,
                    response_serializer=proto_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'BatchInitUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInitUsers,
                    request_deserializer=proto_dot_payment__pb2.BatchUserInitRequest.FromString,
                    response_serializer=proto_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/CreateUser',
            proto_dot_common__pb2.Empty.SerializeToString,
            proto_dot_payment__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/AddFunds',
            proto_dot_payment__pb2.AddFundsRequest.SerializeToString,
            proto_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/ProcessPayment',
            proto_dot_payment__pb2.PaymentRequest.SerializeToString,
            proto_dot_payment__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInitUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/BatchInitUsers',
            proto_dot_payment__pb2.BatchUserInitRequest.SerializeToString,
            proto_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
