# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/stock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/stock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/stock.proto\x12\x05stock\x1a\x12proto/common.proto\"5\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x05\"\"\n\x11\x43reateItemRequest\x12\r\n\x05price\x18\x01 \x01(\x05\"%\n\x12\x43reateItemResponse\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"\x1e\n\x0bItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"4\n\x0fStockAdjustment\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"V\n\x15\x42\x61tchStockInitRequest\x12\x11\n\tnum_items\x18\x01 \x01(\x05\x12\x16\n\x0estarting_stock\x18\x02 \x01(\x05\x12\x12\n\nitem_price\x18\x03 \x01(\x05\x32\xa6\x02\n\x0cStockService\x12\x41\n\nCreateItem\x12\x18.stock.CreateItemRequest\x1a\x19.stock.CreateItemResponse\x12+\n\x08\x46indItem\x12\x12.stock.ItemRequest\x1a\x0b.stock.Item\x12\x31\n\x08\x41\x64\x64Stock\x12\x16.stock.StockAdjustment\x1a\r.common.Empty\x12\x34\n\x0bRemoveStock\x12\x16.stock.StockAdjustment\x1a\r.common.Empty\x12=\n\x0e\x42\x61tchInitItems\x12\x1c.stock.BatchStockInitRequest\x1a\r.common.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=48
  _globals['_ITEM']._serialized_end=101
  _globals['_CREATEITEMREQUEST']._serialized_start=103
  _globals['_CREATEITEMREQUEST']._serialized_end=137
  _globals['_CREATEITEMRESPONSE']._serialized_start=139
  _globals['_CREATEITEMRESPONSE']._serialized_end=176
  _globals['_ITEMREQUEST']._serialized_start=178
  _globals['_ITEMREQUEST']._serialized_end=208
  _globals['_STOCKADJUSTMENT']._serialized_start=210
  _globals['_STOCKADJUSTMENT']._serialized_end=262
  _globals['_BATCHSTOCKINITREQUEST']._serialized_start=264
  _globals['_BATCHSTOCKINITREQUEST']._serialized_end=350
  _globals['_STOCKSERVICE']._serialized_start=353
  _globals['_STOCKSERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)
