# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import common_pb2 as proto_dot_common__pb2
from proto import stock_pb2 as proto_dot_stock__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/stock_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/stock.StockService/CreateItem',
                request_serializer=proto_dot_stock__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=proto_dot_stock__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.FindItem = channel.unary_unary(
                '/stock.StockService/FindItem',
                request_serializer=proto_dot_stock__pb2.ItemRequest.SerializeToString,
                response_deserializer=proto_dot_stock__pb2.Item.FromString,
                _registered_method=True)
        self.AddStock = channel.unary_unary(
                '/stock.StockService/AddStock',
                request_serializer=proto_dot_stock__pb2.StockAdjustment.SerializeToString,
                response_deserializer=proto_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveStock = channel.unary_unary(
                '/stock.StockService/RemoveStock',
                request_serializer=proto_dot_stock__pb2.StockAdjustment.SerializeToString,
                response_deserializer=proto_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.BatchInitItems = channel.unary_unary(
                '/stock.StockService/BatchInitItems',
                request_serializer=proto_dot_stock__pb2.BatchStockInitRequest.SerializeToString,
                response_deserializer=proto_dot_common__pb2.Empty.FromString,
                _registered_method=True)


class StockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInitItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=proto_dot_stock__pb2.CreateItemRequest.FromString,
                    response_serializer=proto_dot_stock__pb2.CreateItemResponse.SerializeToString,
            ),
            'FindItem': grpc.unary_unary_rpc_method_handler(
                    servicer.FindItem,
                    request_deserializer=proto_dot_stock__pb2.ItemRequest.FromString,
                    response_serializer=proto_dot_stock__pb2.Item.SerializeToString,
            ),
            'AddStock': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStock,
                    request_deserializer=proto_dot_stock__pb2.StockAdjustment.FromString,
                    response_serializer=proto_dot_common__pb2.Empty.SerializeToString,
            ),
            'RemoveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveStock,
                    request_deserializer=proto_dot_stock__pb2.StockAdjustment.FromString,
                    response_serializer=proto_dot_common__pb2.Empty.SerializeToString,
            ),
            'BatchInitItems': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInitItems,
                    request_deserializer=proto_dot_stock__pb2.BatchStockInitRequest.FromString,
                    response_serializer=proto_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stock.StockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stock.StockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockService/CreateItem',
            proto_dot_stock__pb2.CreateItemRequest.SerializeToString,
            proto_dot_stock__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockService/FindItem',
            proto_dot_stock__pb2.ItemRequest.SerializeToString,
            proto_dot_stock__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockService/AddStock',
            proto_dot_stock__pb2.StockAdjustment.SerializeToString,
            proto_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockService/RemoveStock',
            proto_dot_stock__pb2.StockAdjustment.SerializeToString,
            proto_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInitItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stock.StockService/BatchInitItems',
            proto_dot_stock__pb2.BatchStockInitRequest.SerializeToString,
            proto_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
